name: firebase_chat
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^2.7.1
  firebase_auth: ^4.2.10
  firebase_storage: ^11.0.15
  firebase_remote_config: ^3.0.14
  get: ^4.6.5
  dots_indicator: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_cupertino_localizations: ^1.0.1
  cupertino_icons: ^1.0.2
  intl: ^0.17.0
  flutter_screenutil: ^5.3.1
  pull_to_refresh: ^2.0.0
  fluttertoast: ^8.0.9
  flutter_easyloading: ^3.0.3
  dio: ^4.0.4
  dio_cookie_manager: ^2.0.0
  cookie_jar: ^3.0.1
  shared_preferences: ^2.0.13
  cached_network_image: ^3.2.0
  flutter_cache_manager: ^3.3.0
  crypto: ^3.0.1
  webview_flutter: ^4.0.0
  loading_animations: ^2.2.0
  share: ^2.0.4
  device_info: ^2.0.3
  package_info: ^2.0.2
  path_provider: ^2.0.9
  permission_handler: ^10.2.0
  sentry: ^6.3.0
  uni_links: ^0.5.1
  flutter_spinkit: ^5.1.0
  flutter_swiper: ^1.1.6
  google_sign_in: ^5.3.3
  firebase_messaging: ^14.1.4
  firebase_in_app_messaging: ^0.7.0+8
  location: ^4.4.0
  image_picker: ^0.8.7
  cloud_firestore: ^4.4.4
  photo_view: ^0.14.0
  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/images/
    - assets/icons/

  fonts:
    - family: Avenir
      fonts: 
        - asset: assets/fonts/Avenir-Book.ttf
          weight: 400
    - family: Montserrat
      fonts: 
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
    - family: Iconfont
      fonts: 
        - asset: assets/fonts/iconfont.ttf
          weight: 400
